#!/bin/bash
# from https://github.com/priyaasrini/AlgJulia-Book-Binder2
set -e  # don't allow errors to fail silently
julia --project=. --threads=auto --startup-file=no --heap-size-hint=1G -e '
using Pkg;
Pkg.add("MTH229");
Pkg.add("Plots");
exit();
'
